name: ccolor
base: core24
version: '0.3.0'
summary: Color highlighting in the Bash command line.
description: |
  Color highlighting in the Bash command line.
  Bashコマンド用に特定の文字に色を付けるハイライト機能。

  It highlights patterns that require attention in logs.
  ログの表示等で注意すべき文字をハイライトできます。
grade: devel # devel/stable
confinement: classic # strict/classic/devmode
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

